:hardbreaks-option:

== 디자인 패턴 감 잡기

**디자인 패턴**은 소프트웨어 설계 중 발생하는 자주 발생하는 문제를 풀어내기 위한 해결방법이다. 이는 어떠한 명확한 코드가 아니라, 특정 문제를 해결하기 위한 General Concept이다. 알고리즘은 항상 어떠한 목표를 달성할 수 있는 일련의 과정들을 명확히 정의한다면, 디자인 패턴은 어떠한 해결방법에 대한 추상적인 묘사의 방법이다. 때문에 동일한 패턴을 적용한 두 프로그램의 구현 코드는 서로 다를 수 있다. 비유를 하자면 알고리즘은 요리 레시피, 디자인 패턴은 청사진이라고 할 수 있다.

=== 왜 배울까

* 디자인 패턴은 소프트웨어 설계의 자주 등장하는 문제들을 위한 시도 & 테스트해보기 위한 일종의 Toolkit 이다. 관련 문제를 직면하지 않더라도, 패턴을 알고 있는 것은 객체지향 설계의 원리를 이용하여 다양한 종류의 문제를 해결하는 방법을 가르쳐주기 때문에 유용하다.

* 디자인 패턴은 동료들과 함께 효율적으로 소통할 수 있는 공용 용어를 정의해준다. "그 부분은 싱글톤을 사용해줘" 라고 말하면, 쉽게 어떤 얘기인 지 이해할 수 있다. 패턴과 그 이름을 안다면 싱글톤에 대한 부연 설명이 필요하지 않게 된다.

=== 패턴의 분류

디자인 패턴은 각 패턴 별 복잡성 및 세부 수준, 설계되는 전체 시스템에 대한 적용 가능 규모에 따라 구분된다. 가장 기본적이며 Low-level의 패턴들은 **idioms** (관용구) 라고 불린다. 가장 보편성을 띄고 High-level의 패턴들은 **Architectural Patterns**라고 불린다.

* Creational Pattern (생성 패턴)
기존 코드의 유연성과 재사용성을 증진시켜주는 객체 생성에 관한 메커니즘을 제공

* Structural Pattern (구조 패턴)
구조를 유연하고 효율적으로 유지하면서 객체와 클래스를 더 큰 구조로 만듦

* Behavioral Pattern (행동 패턴)
코드 상의 효과적인 소통 및 객체 간의 책임 할당을 처리
